### ISSUE TITLE
Problem with cacoo macro in confluence wiki

### ISSUE THREAD

**Issue by sarahstxt** [shoito/cacoo-confluence#2]
Hi, 

since Confluence 5.9 we cannot use the Cacoo Macro anymore, we always receive the following error:

Error rendering macro 'cacoo' : loader constraint violation: when resolving method "com.atlassian.confluence.util.velocity.VelocityUtils.getRenderedTemplate(Ljava/lang/String;Lorg/apache/velocity/context/Context;)Ljava/lang/String;" the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) of the current class, com/github/shoito/confluence/integration/cacoo/macro/CacooMacro, and the class loader (instance of org/apache/catalina/loader/WebappClassLoader) for the method's defining class, com/atlassian/confluence/util/velocity/VelocityUtils, have different Class objects for the type org/apache/velocity/context/Context used in the signature

We are running Confluence on a Centos 7 Server with openjdk Version 1.8.0_45

Could you help me fixing this Bug please

I already tried to re-install the pluging and it didn't help

Best Regards
Sarah

**Comment by shoito** [comment]
@sarahstxt 
Thank you very much for reporting.
I will fix this bug. Please wait for a while.

**Comment by sarahstxt** [comment]
Hi, 
do you have anynews for this Issue?

BR
Sarah

**Comment by SalvadorGrupoSM** [comment]
I have the same problem. Any news about the fix?

**Comment by shoito** [comment]
@sarahstxt @SalvadorGrupoSM 
the new version was released, so please check it.

**Comment by sarahstxt** [comment]
Hello,

thank you very much for the update, 
the fix is working 

Best Regards
Sarah
